version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://api:3001/api
    depends_on:
      - api
    networks:
      - lifesheet-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lifesheet
    depends_on:
      - db
    networks:
      - lifesheet-network

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lifesheet
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
    networks:
      - lifesheet-network

volumes:
  postgres_data:

networks:
  lifesheet-network:
    driver: bridge
